stages:
  - test
  - build

include:
    - project: cedaci/ci-tools
      file: /includes/kubernetes.yml

test:item-descriptions:
  stage: test
  image: python:3.8
  before_script:
    - pip install git+https://github.com/cedadev/item_description_validator
  script:
    - item-desc-validator descriptions/

.build_common:
  extends: .build_docker
  variables:
    IMAGE_REPO_BASE: registry.ceda.ac.uk/stac-indexer
    BUILD_ARG_BASE_IMAGES_VERSION: "c821a577"

# Build the item generator image
build:item_generator:
  extends: .build_common
  stage: build
  variables:
    REPOSITORY: $IMAGE_REPO_BASE/item-descriptions
  only:
    - master



IMAGE_REPO_BASE: registry.ceda.ac.uk/stac-indexer